## Task 1: Read CSV File

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/ramen-ratings.csv')
df.head()

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
0,2580,New Touch,T's Restaurant Tantanmen,Cup,Japan,3.75,NaN
1,2579,Just Way,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Pack,Taiwan,1,NaN
2,2578,Nissin,Cup Noodles Chicken Vegetable,Cup,USA,2.25,NaN
3,2577,Wei Lih,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75,NaN
4,2576,Ching's Secret,Singapore Curry,Pack,India,3.75,NaN

## Task 2: Index Selection and Label Selection

In [ ]:
# 2.1 First 10 rows using (iloc)
df.iloc[:10]

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
0,2580,New Touch,T's Restaurant Tantanmen,Cup,Japan,3.75,NaN
1,2579,Just Way,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Pack,Taiwan,1,NaN
2,2578,Nissin,Cup Noodles Chicken Vegetable,Cup,USA,2.25,NaN
3,2577,Wei Lih,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75,NaN
4,2576,Ching's Secret,Singapore Curry,Pack,India,3.75,NaN
5,2575,Samyang Foods,Kimchi song Song Ramen,Pack,South Korea,4.75,NaN
6,2574,Acecook,Spice Deli Tantan Men With Cilantro,Cup,Japan,4,NaN
7,2573,Ikeda Shoku,Nabeyaki Kitsune Udon,Tray,Japan,3.75,NaN
8,2572,Ripe'n'Dry,Hokkaido Soy Sauce Ramen,Pack,Japan,0.25,NaN
9,2571,KOKA,The Original Spicy Stir-Fried Noodles,Pack,Singapore,2.5,NaN

In [ ]:
# 2.1 First 10 rows using (loc)
df.loc[0:9]

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
0,2580,New Touch,T's Restaurant Tantanmen,Cup,Japan,3.75,NaN
1,2579,Just Way,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Pack,Taiwan,1,NaN
2,2578,Nissin,Cup Noodles Chicken Vegetable,Cup,USA,2.25,NaN
3,2577,Wei Lih,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75,NaN
4,2576,Ching's Secret,Singapore Curry,Pack,India,3.75,NaN
5,2575,Samyang Foods,Kimchi song Song Ramen,Pack,South Korea,4.75,NaN
6,2574,Acecook,Spice Deli Tantan Men With Cilantro,Cup,Japan,4,NaN
7,2573,Ikeda Shoku,Nabeyaki Kitsune Udon,Tray,Japan,3.75,NaN
8,2572,Ripe'n'Dry,Hokkaido Soy Sauce Ramen,Pack,Japan,0.25,NaN
9,2571,KOKA,The Original Spicy Stir-Fried Noodles,Pack,Singapore,2.5,NaN

In [ ]:
# 2.2 Rows 2560-2565: Brand and Stars
df.loc[2560:2565, ['Brand', 'Stars']]

          Brand Stars
2560   Nongshim   3.5
2561   Nongshim     4
2562     Ottogi   3.5
2563  Quickchow   2.5
2564    Samyang   3.5
2565    Samyang   2.5

## Task 3: Conditional Selection

### 3.1

In [ ]:
df[df['Country'] == 'Japan']

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
0,2580,New Touch,T's Restaurant Tantanmen,Cup,Japan,3.75,NaN
6,2574,Acecook,Spice Deli Tantan Men With Cilantro,Cup,Japan,4,NaN
7,2573,Ikeda Shoku,Nabeyaki Kitsune Udon,Tray,Japan,3.75,NaN
8,2572,Ripe'n'Dry,Hokkaido Soy Sauce Ramen,Pack,Japan,0.25,NaN
13,2567,Nissin,Deka Buto Kimchi Pork Flavor,Bowl,Japan,4.5,NaN
...,...,...,...,...,...,...,...
2554,26,Nissin,Soba Noodles With Mayo Mustard Squirt,Pack,Japan,4,NaN
2555,25,Nissin,Demae Ramen Spicy Flavor,Pack,Japan,3,NaN
2556,24,Nissin,Demae Ramen Spicy Seafood With Chili Pepper,Pack,Japan,2,NaN
2567,13,Sapporo Ichiban,Chow Mein,Pack,Japan,5,2012 #4
2568,12,Sapporo Ichiban,Shrimp Flavor,Pack,Japan,2.5,NaN

### 3.2

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2580 entries, 0 to 2579
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Review #  2580 non-null   int64
 1   Brand     2580 non-null   object
 2   Variety   2580 non-null   object
 3   Style     2578 non-null   object
 4   Country   2580 non-null   object
 5   Stars     2580 non-null   object
 6   Top Ten   41 non-null     object
dtypes: int64(1), object(6)
memory usage: 141.2+ KB

In [ ]:
df['Stars'].unique()

array(['3.75', '1', '2.25', '2.75', '4.75', '4', '0.25', '2.5', '5',
       '4.25', '4.5', '3.5', 'Unrated', '1.5', '3.25', '2', '0', '3',
       '0.5', '4.00', '5.0', '3.50', '3.8', '4.3', '2.3', '5.00', '3.3',
       '4.0', '3.00', '1.75', '3.0', '4.50', '0.75', '1.25', '1.1', '2.1',
       '0.9', '3.1', '4.125', '3.125', '2.125', '2.9', '0.1', '2.8',
       '3.7', '3.4', '3.6', '2.85', '3.2', '3.65', '1.8'], dtype=object)

In [ ]:
df['Stars'] = df['Stars'].str.replace('Unrated', '0')
df['Stars'].unique()

array(['3.75', '1', '2.25', '2.75', '4.75', '4', '0.25', '2.5', '5',
       '4.25', '4.5', '3.5', '0', '1.5', '3.25', '2', '3', '0.5', '4.00',
       '5.0', '3.50', '3.8', '4.3', '2.3', '5.00', '3.3', '4.0', '3.00',
       '1.75', '3.0', '4.50', '0.75', '1.25', '1.1', '2.1', '0.9', '3.1',
       '4.125', '3.125', '2.125', '2.9', '0.1', '2.8', '3.7', '3.4',
       '3.6', '2.85', '3.2', '3.65', '1.8'], dtype=object)

In [ ]:
df['Stars'] = df['Stars'].astype(float)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2580 entries, 0 to 2579
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Review #  2580 non-null   int64
 1   Brand     2580 non-null   object
 2   Variety   2580 non-null   object
 3   Style     2578 non-null   object
 4   Country   2580 non-null   object
 5   Stars     2580 non-null   float64
 6   Top Ten   41 non-null     object
dtypes: float64(1), int64(1), object(5)
memory usage: 141.2+ KB

In [ ]:
df[df['Stars'] >= 4.5]

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
5,2575,Samyang Foods,Kimchi song Song Ramen,Pack,South Korea,4.75,NaN
10,2570,Tao Kae Noi,Creamy tom Yum Kung Flavour,Pack,Thailand,5.00,NaN
11,2569,Yamachan,Yokohama Tonkotsu Shoyu,Pack,USA,5.00,NaN
13,2567,Nissin,Deka Buto Kimchi Pork Flavor,Bowl,Japan,4.50,NaN
14,2566,Nissin,Demae Ramen Bar Noodle Aka Tonkotsu Flavour In...,Pack,Hong Kong,5.00,NaN
...,...,...,...,...,...,...,...
2533,47,Indomie,Mi Goreng Jumbo Barbecue Chicken,Pack,Indonesia,5.00,2012 #2
2535,45,Indomie,Mi Goreng Sate,Pack,Indonesia,5.00,\n
2552,28,Nissin,Chikin Ramen,Pack,Japan,5.00,NaN
2557,23,Nissin,Top Ramen Creamy Chicken,Pack,USA,4.50,NaN
2567,13,Sapporo Ichiban,Chow Mein,Pack,Japan,5.00,2012 #4

### 3.3

In [ ]:
df[(df['Style'] == "Cup") & (df['Country'] == "USA")]

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
2,2578,Nissin,Cup Noodles Chicken Vegetable,Cup,USA,2.25,NaN
39,2541,Nissin,Cup Noodles Very Veggie Spicy Chicken Flavor R...,Cup,USA,5.00,NaN
42,2538,Nissin,Cup Noodles Very Veggie Beef Flavor Ramen Nood...,Cup,USA,5.00,NaN
45,2535,Nissin,Cup Noodles Very Veggie Chicken Flavor Ramen N...,Cup,USA,5.00,NaN
154,2426,Dr. McDougall's,Vegan Pad Thai Noodle Soup,Cup,USA,0.00,NaN
...,...,...,...,...,...,...,...
2324,256,Nissin,Cup Noodles Shrimp,Cup,USA,3.50,NaN
2364,216,Maruchan,Instant Lunch Roast Chicken Flavor,Cup,USA,2.75,NaN
2424,156,Maruchan,Instant Lunch Cajun Style With chili Piquin Sh...,Cup,USA,3.00,NaN
2426,154,Nissin,Creamy Chicken,Cup,USA,1.75,NaN
2427,153,Sapporo Ichiban,Shrimp Flavor,Cup,USA,1.75,NaN

## Task 4: Assign New Column

In [ ]:
# 1
def rating(row):
  if row['Stars'] >= 4:
    return 'Excellent'
  else:
    return 'Good'

df['Rating_Category'] = df.apply(rating, axis=1)
df

,Review #,Brand,Variety,Style,Country,Stars,Top Ten,Rating_Category
0,2580,New Touch,T's Restaurant Tantanmen,Cup,Japan,3.75,NaN,Good
1,2579,Just Way,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Pack,Taiwan,1.00,NaN,Good
2,2578,Nissin,Cup Noodles Chicken Vegetable,Cup,USA,2.25,NaN,Good
3,2577,Wei Lih,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75,NaN,Good
4,2576,Ching's Secret,Singapore Curry,Pack,India,3.75,NaN,Good
...,...,...,...,...,...,...,...,...
2575,5,Vifon,"Hu Tiu Nam Vang [""Phnom Penh"" style] Asian Sty...",Bowl,Vietnam,3.50,NaN,Good
2576,4,Wai Wai,Oriental Style Instant Noodles,Pack,Thailand,1.00,NaN,Good
2577,3,Wai Wai,Tom Yum Shrimp,Pack,Thailand,2.00,NaN,Good
2578,2,Wai Wai,Tom Yum Chili Flavor,Pack,Thailand,2.00,NaN,Good
2579,1,Westbrae,Miso Ramen,Pack,USA,0.50,NaN,Good

In [ ]:
# 2
df['Rating_Category'].head(10)

0         Good
1         Good
2         Good
3         Good
4         Good
5    Excellent
6    Excellent
7         Good
8         Good
9         Good
Name: Rating_Category, dtype: object